## Ucitavanje i Sredjivanje Nizova Podataka

In [77]:
#ucitavanje potrebnih biblioteka
import pandas as pd
import numpy as np

In [78]:
#uvoz podataka
#sezona 23/24
df_23_4 = pd.read_csv("championship-2023.csv")
#sezona 24/25
df_24_5 = pd.read_csv("championship-2024.csv")
#sezona 25/6
df_25_6 = pd.read_csv("championship-2025.csv")

## Određivanje Duzine Trenutnoj Sezoni i Prikaz

In [79]:
#odrediti duzinu sezone - OBAVEZNO!!!
df_25_6 = df_25_6.head(60)
df_25_6.tail()

,Match Number,Round Number,Date,Location,Home Team,Away Team,Result
55,57,5,13/09/2025 15:00,Swansea.com Stadium,Swansea City,Hull City,2 - 2
56,58,5,13/09/2025 15:00,Vicarage Road,Watford,Blackburn Rovers,0 - 1
57,59,5,13/09/2025 15:00,The Hawthorns,West Bromwich Albion,Derby County,0 - 1
58,60,5,13/09/2025 15:00,SToK Cae Ras,Wrexham,Queens Park Rangers,1 - 3
59,55,5,14/09/2025 12:00,St. Mary's Stadium,Southampton,Portsmouth,0 - 0

In [80]:
#sjedinjavanje ta tri df niza podataka - po osi jedan - odnosno uzduž
df_BL = pd.concat([df_23_4, df_24_5, df_25_6], axis=0)

In [81]:
#prikaz sjedinjenog niza podatak 
#tj. sve tri sezone u jednom nizu podataka u obliku df 
df_BL.tail()

,Match Number,Round Number,Date,Location,Home Team,Away Team,Result
55,57,5,13/09/2025 15:00,Swansea.com Stadium,Swansea City,Hull City,2 - 2
56,58,5,13/09/2025 15:00,Vicarage Road,Watford,Blackburn Rovers,0 - 1
57,59,5,13/09/2025 15:00,The Hawthorns,West Bromwich Albion,Derby County,0 - 1
58,60,5,13/09/2025 15:00,SToK Cae Ras,Wrexham,Queens Park Rangers,1 - 3
59,55,5,14/09/2025 12:00,St. Mary's Stadium,Southampton,Portsmouth,0 - 0

## Predprocesovanje Niza Podataka

In [82]:
#Izbacivanje Nerelevantnih Osobina
df_BL = df_BL.drop(["Match Number","Round Number","Date","Location"],axis=1)
df_BL.shape

(1164, 3)

In [83]:
df_BL.rename(columns={"Home Team":"H","Away Team":"A"},inplace=True)

In [84]:
df_BL.to_csv("cship.csv")
df_BL

                       H                     A Result
0    Sheffield Wednesday           Southampton  1 - 2
1       Blackburn Rovers  West Bromwich Albion  2 - 1
2           Bristol City     Preston North End  1 - 1
3          Middlesbrough              Millwall  0 - 1
4           Norwich City             Hull City  2 - 1
..                   ...                   ...    ...
55          Swansea City             Hull City  2 - 2
56               Watford      Blackburn Rovers  0 - 1
57  West Bromwich Albion          Derby County  0 - 1
58               Wrexham   Queens Park Rangers  1 - 3
59           Southampton            Portsmouth  0 - 0

[1164 rows x 3 columns]

In [85]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

#One Hot Encoder Timova - Domacin i Gost
onehot_encoder_domacin = OneHotEncoder(handle_unknown="ignore",drop="first")  # Ensure parameters are correct
kodiran_domacin = onehot_encoder_domacin.fit_transform(df_BL[["H"]]).toarray()
df_domacin = pd.DataFrame(kodiran_domacin,columns=onehot_encoder_domacin.get_feature_names_out(["H"]))

In [86]:
df_domacin.columns

Index(['H_Blackburn Rovers', 'H_Bristol City', 'H_Burnley', 'H_Cardiff City',
       'H_Charlton Athletic', 'H_Coventry City', 'H_Derby County',
       'H_Huddersfield Town', 'H_Hull City', 'H_Ipswich Town',
       'H_Leeds United', 'H_Leicester City', 'H_Luton Town', 'H_Middlesbrough',
       'H_Millwall', 'H_Norwich City', 'H_Oxford United', 'H_Plymouth Argyle',
       'H_Portsmouth', 'H_Preston North End', 'H_Queens Park Rangers',
       'H_Rotherham United', 'H_Sheffield United', 'H_Sheffield Wednesday',
       'H_Southampton', 'H_Stoke City', 'H_Sunderland', 'H_Swansea City',
       'H_Watford', 'H_West Bromwich Albion', 'H_Wrexham'],
      dtype='object')

In [87]:
df_domacin.shape

(1164, 31)

In [88]:
#One Hot Encoder Timova - Gosti
onehot_encoder_gost = OneHotEncoder(handle_unknown="ignore",drop="first")  # Ensure parameters are correct
kodiran_gost = onehot_encoder_gost.fit_transform(df_BL[["A"]]).toarray()
df_gost = pd.DataFrame(kodiran_gost,columns=onehot_encoder_gost.get_feature_names_out(["A"]))

In [89]:
df_gost.shape

(1164, 31)

In [90]:
#Sjedinjavanje tih osobina domacin i gost
df_jedan = pd.concat([df_domacin,df_gost],axis=1)
df_jedan

,H_Blackburn Rovers,H_Bristol City,H_Burnley,H_Cardiff City,H_Charlton Athletic,H_Coventry City,H_Derby County,H_Huddersfield Town,H_Hull City,H_Ipswich Town,...,A_Rotherham United,A_Sheffield United,A_Sheffield Wednesday,A_Southampton,A_Stoke City,A_Sunderland,A_Swansea City,A_Watford,A_West Bromwich Albion,A_Wrexham
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1159,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1160,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1161,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1162,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1163,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Transformisanje Rezultata u Varijablu - Y Varijable

#### Stvaranje Vrijednosti za Dvije Kolone iz Jedne Osobine/Kolone Rezultat

In [91]:
rez_dom = df_BL["Result"].str.slice(0,1)

In [92]:
rez_dom.head()

0    1
1    2
2    1
3    0
4    2
Name: Result, dtype: object

In [93]:
rez_gost = df_BL["Result"].str.slice(4,5)

In [94]:
rez_gost.head()

0    2
1    1
2    1
3    1
4    1
Name: Result, dtype: object

In [95]:
df_rezultatski = pd.concat([df_BL,rez_dom,rez_gost],axis=1)

In [96]:
#promjena naziva kolonama - spajanjem smo dobili kolone istih naziva
df_rezultatski.columns = ["H","A","Result","Rez1","Rez2"]
df_rezultatski

                       H                     A Result Rez1 Rez2
0    Sheffield Wednesday           Southampton  1 - 2    1    2
1       Blackburn Rovers  West Bromwich Albion  2 - 1    2    1
2           Bristol City     Preston North End  1 - 1    1    1
3          Middlesbrough              Millwall  0 - 1    0    1
4           Norwich City             Hull City  2 - 1    2    1
..                   ...                   ...    ...  ...  ...
55          Swansea City             Hull City  2 - 2    2    2
56               Watford      Blackburn Rovers  0 - 1    0    1
57  West Bromwich Albion          Derby County  0 - 1    0    1
58               Wrexham   Queens Park Rangers  1 - 3    1    3
59           Southampton            Portsmouth  0 - 0    0    0

[1164 rows x 5 columns]

In [97]:
#spremanje df_epl varijable za obradu osobine Result u excelu
df_rezultatski.to_csv("uredjivanje_skora_vani.csv")

## Uocavanje Indeksa Sezona - za Kasnije Floatiranje

In [98]:
#df_rezultatski[0:552] #sezona 23/4 od 0:552
#df_rezultatski[552:1104] #sezona 24/5 od 552:1104
#df_rezultatski[1104:] #sezona25/6 od 1104:

## Stvaranje Kolone Skor sa Vrijednostima - Ovdje

In [99]:
# Define a function to perform the conditional logic
def calculate_value(row):
    if row['Rez1'] > row['Rez2']:
        return 1
    elif row['Rez1'] < row['Rez2']:
        return -1
    else:  # row['Column1'] == row['Column2']
        return 0

In [100]:
# Apply the function to each row in the DataFrame and assign the result to a new column
df_rezultatski['Skor'] = df_rezultatski.apply(calculate_value, axis=1)
skor = df_rezultatski.drop(['H', 'A', 'Result', 'Rez1',"Rez2"],axis=1)

### Floatiranje Vrijednosti Kolone Skor - po Sezonama

#df_rezultatski[0:552] #sezona 23/4 od 0:552
#df_rezultatski[552:1104] #sezona 24/5 od 552:1104
#df_rezultatski[1104:] #sezona25/6 od 1104:

In [101]:
#sezona 23/4
skor23_4 = skor[0:552]
skor24_5 = skor[552:1104]
skor25_6 = skor[1104:]

In [102]:
#skor.head(3)
skor23_4["Skor"] = skor23_4["Skor"] * 0.71

C:\Users\amirb\AppData\Local\Temp\ipykernel_6800\3544292283.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  skor23_4["Skor"] = skor23_4["Skor"] * 0.71

In [103]:
skor24_5["Skor"] = skor24_5["Skor"] * 0.85

C:\Users\amirb\AppData\Local\Temp\ipykernel_6800\3136881136.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  skor24_5["Skor"] = skor24_5["Skor"] * 0.85

## Konačna kolona Skor - Sjedinjavanje Vrijednosti Sezona

In [104]:
skor = pd.concat([skor23_4, skor24_5, skor25_6], axis=0, ignore_index=True)

Provjera se vrši manuelno, gledanjem repa,glave i sredine ovog df-a

In [105]:
df_rezultatski = df_rezultatski.reset_index(drop=True)
skor = skor.reset_index(drop=True)

In [106]:
#provjera rezultata
finalna_provjera = pd.concat([df_rezultatski,skor],axis=1,ignore_index=True)
finalna_provjera = finalna_provjera.drop([3,4,5],axis=1)
finalna_provjera.columns = ["H","A","Rezultat","Skor"]

In [108]:
finalna_provjera.head()

                     H                     A Rezultat  Skor
0  Sheffield Wednesday           Southampton    1 - 2 -0.71
1     Blackburn Rovers  West Bromwich Albion    2 - 1  0.71
2         Bristol City     Preston North End    1 - 1  0.00
3        Middlesbrough              Millwall    0 - 1 -0.71
4         Norwich City             Hull City    2 - 1  0.71

# Konačni df - Podaci su Sređeni

In [109]:
skor = skor.reset_index(drop=True)
df_jedan = df_jedan.reset_index(drop=True)

In [110]:
df_BL = pd.concat([df_jedan,skor],axis=1)

In [111]:
df_BL.head(5)

,H_Blackburn Rovers,H_Bristol City,H_Burnley,H_Cardiff City,H_Charlton Athletic,H_Coventry City,H_Derby County,H_Huddersfield Town,H_Hull City,H_Ipswich Town,...,A_Sheffield United,A_Sheffield Wednesday,A_Southampton,A_Stoke City,A_Sunderland,A_Swansea City,A_Watford,A_West Bromwich Albion,A_Wrexham,Skor
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.71
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.71
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.71
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.71

In [112]:
#spremanje kodiranog niza podataka
df_BL.to_csv("kodirani_bl.csv")

## Razdvajanje Niza Podataka na Osobine za Predvidjanje i Ciljanu Osobinu

In [113]:
# X predvidjacke, y varijabla jeste Skor Osobina
X = df_BL.drop(["Skor"],axis=1)
y = df_BL["Skor"]

In [114]:
#razdvajanje podataka u treniranju i testirajuce nizove
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1,random_state=42)
X_train.head()

,H_Blackburn Rovers,H_Bristol City,H_Burnley,H_Cardiff City,H_Charlton Athletic,H_Coventry City,H_Derby County,H_Huddersfield Town,H_Hull City,H_Ipswich Town,...,A_Rotherham United,A_Sheffield United,A_Sheffield Wednesday,A_Southampton,A_Stoke City,A_Sunderland,A_Swansea City,A_Watford,A_West Bromwich Albion,A_Wrexham
783,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
582,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
796,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
807,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [115]:
#skaliranje ovih osobina
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[-0.20695092, -0.21436895, -0.13954998, ..., -0.19930365,
        -0.20442858, -0.03091962],
       [-0.20695092, -0.21436895, -0.13954998, ..., -0.19930365,
        -0.20442858, -0.03091962],
       [-0.20695092, -0.21436895, -0.13954998, ..., -0.19930365,
        -0.20442858, -0.03091962],
       ...,
       [-0.20695092, -0.21436895, -0.13954998, ..., -0.19930365,
        -0.20442858, -0.03091962],
       [-0.20695092, -0.21436895, -0.13954998, ..., -0.19930365,
        -0.20442858, -0.03091962],
       [-0.20695092, -0.21436895, -0.13954998, ..., -0.19930365,
        -0.20442858, -0.03091962]])

In [116]:
#Spremanje tog Kodera - za Kasniju Upotrebu

with open("onehot_encoder_domacin.pkl","wb") as file:
    pickle.dump(onehot_encoder_domacin,file)
    
with open("onehot_encoder_gost.pkl","wb") as file:
    pickle.dump(onehot_encoder_gost,file)
    
with open("scaler.pkl","wb") as file:
    pickle.dump(scaler,file)

## Stvaranje Modela i Dobijanje Predikcije

In [117]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
#sledeca biblioteka se odnosi na stvaranje neurona iz kutije layers i alatom dense
from tensorflow.keras.layers import Dense

In [118]:
#konstrukcija modela
model=Sequential([
    Dense(16,activation="relu",input_shape=(X_train.shape[1],)), #HL1 connected to I/p - Skriveni Sloj 1 povezan sa I/p
    Dense(1)
])

In [119]:
#Oblikovanje Modela 
model.compile(optimizer="adam",loss="mean_absolute_error",metrics=["mae"])
model.summary()

# Keras dokumentacija pojasnjava sta se dogodi sa razlicitim odabirom "loss" i drugih parametara

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 16)                1008

 dense_1 (Dense)             (None, 1)                 17

=================================================================
Total params: 1,025
Trainable params: 1,025
Non-trainable params: 0
_________________________________________________________________

In [120]:
import datetime
#uspostavljanje Tensorboard-a, zapocinjanje treniranja
#TensorBoard sluzi samo za vizualizaciju svih logovanja koje izvrsim kod treniranja nekog modela
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

#log_dir varijabla koja osigurava da ostane zabinjezen trag svakog treniranja modela
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

#Uspostavljanje Early Stopping - sluzi za zaustavljanje treniranja ako se vrijednost gubitaka ne smanjuje
#bitni parametri su uneseni koji sluze poboljsanju funkcije ranog zaustavljanja treniranja modela...
early_stopping_callback = EarlyStopping(monitor="val_loss",patience=10,restore_best_weights=True)

In [121]:
#TRENIRANJE MODELA / Tovarenje Modela
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

history = model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=50,
    callbacks= [tensorflow_callback,early_stopping_callback]
)

Epoch 1/50
33/33 [==============================] - 7s 70ms/step - loss: 0.9672 - mae: 0.9672 - val_loss: 0.8395 - val_mae: 0.8395
Epoch 2/50
33/33 [==============================] - 1s 16ms/step - loss: 0.7930 - mae: 0.7930 - val_loss: 0.7097 - val_mae: 0.7097
Epoch 3/50
33/33 [==============================] - 1s 17ms/step - loss: 0.6895 - mae: 0.6895 - val_loss: 0.6530 - val_mae: 0.6530
Epoch 4/50
33/33 [==============================] - 1s 17ms/step - loss: 0.6286 - mae: 0.6286 - val_loss: 0.6209 - val_mae: 0.6209
Epoch 5/50
33/33 [==============================] - 0s 14ms/step - loss: 0.5925 - mae: 0.5925 - val_loss: 0.6161 - val_mae: 0.6161
Epoch 6/50
33/33 [==============================] - 0s 15ms/step - loss: 0.5735 - mae: 0.5735 - val_loss: 0.6089 - val_mae: 0.6089
Epoch 7/50
33/33 [==============================] - 1s 18ms/step - loss: 0.5563 - mae: 0.5563 - val_loss: 0.6068 - val_mae: 0.6068
Epoch 8/50
33/33 [==============================] - 1s 16ms/step - loss: 0.5447 - mae: 0.5447 - val_loss: 0.6031 - val_mae: 0.6031
Epoch 9/50
33/33 [==============================] - 1s 16ms/step - loss: 0.5329 - mae: 0.5329 - val_loss: 0.6033 - val_mae: 0.6033
Epoch 10/50
33/33 [==============================] - 1s 17ms/step - loss: 0.5223 - mae: 0.5223 - val_loss: 0.6060 - val_mae: 0.6060
Epoch 11/50
33/33 [==============================] - 1s 21ms/step - loss: 0.5140 - mae: 0.5140 - val_loss: 0.6041 - val_mae: 0.6041
Epoch 12/50
33/33 [==============================] - 0s 15ms/step - loss: 0.5071 - mae: 0.5071 - val_loss: 0.6099 - val_mae: 0.6099
Epoch 13/50
33/33 [==============================] - 0s 11ms/step - loss: 0.5026 - mae: 0.5026 - val_loss: 0.6066 - val_mae: 0.6066
Epoch 14/50
33/33 [==============================] - 0s 12ms/step - loss: 0.4947 - mae: 0.4947 - val_loss: 0.6043 - val_mae: 0.6043
Epoch 15/50
33/33 [==============================] - 0s 12ms/step - loss: 0.4881 - mae: 0.4881 - val_loss: 0.6063 - val_mae: 0.6063
Epoch 16/50
33/33 [==============================] - 0s 11ms/step - loss: 0.4832 - mae: 0.4832 - val_loss: 0.6088 - val_mae: 0.6088
Epoch 17/50
33/33 [==============================] - 0s 11ms/step - loss: 0.4781 - mae: 0.4781 - val_loss: 0.6062 - val_mae: 0.6062
Epoch 18/50
33/33 [==============================] - 0s 11ms/step - loss: 0.4728 - mae: 0.4728 - val_loss: 0.6054 - val_mae: 0.6054

In [122]:
#Procjena Rada Modela preko test podataka
test_loss, test_mae = model.evaluate(X_test,y_test)

4/4 [==============================] - 0s 8ms/step - loss: 0.6031 - mae: 0.6031

In [123]:
#spremanje modela
model.save("cship_model.h5")

In [124]:
#moze biti da skaliranje je neophodno, onda je potrebno i obnoviti test parametara modela, te iznova
#-trenirati model i na kraju ga ponovo spremiti.